language: perl

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

env:
  global:
    - KRITIKA_TOKEN=45a42f393b166f02ea8e75fe0669877bdc9d630b

install:
  - "cpanm -n --quiet --installdeps --with-develop ."

after_success:
  - cover -test -report coveralls
  - cover -test -report kritika
